### ISSUE TITLE
Setting RecordMode to 'None' for a Request with no Recorded Cassette Results in MatchNotFoundException

### ISSUE THREAD

**Issue by sdepouw** [epignosisx/vcr.net#3]
Hello,
I was looking for a means to disable VCR.NET recording/playback (while sussing out the external resource / etc., without having to go and delete the newly-created Cassette file after every test run). So, I attempted the following:

```csharp
_vcr.UseCassette(cassetteName, RecordMode.None)
```

- Expected behavior: The HTTP request goes through, with VCR.NET effectively no-oping. No recording, no playback attempts.
- Actual behavior: `MatchNotFoundException` is thrown (if there's no cassette file recorded)

Is there some other way I can inform VCR to basically do nothing for playback and recording so I can just let the HTTP traffic flow through without any VCR interaction?

**Comment by epignosisx** [comment]
@sdepouw the meaning of `RecordMode.None` is that it will not record anything, everything will be playback. None of the `RecordMode` enum values provide the behavior you are expecting. See them all here documented:

https://github.com/epignosisx/vcr.net/blob/master/src/Vcr/RecordMode.cs
